import { useEffect, useState, type FormEvent } from 'react';
import { supabase, loadWorks, emptyWork, categories, slugify, compressImage, signImages, type Work, type WorkImage } from '../lib/works';
import { WorkStory } from '../components/Works';
import './WorksAdmin.css';
const message = (e:unknown) => e instanceof Error ? e.message : (e as {message?:string})?.message || 'Something went wrong. Please try again.';
export default function WorksAdmin(){
 const [auth,setAuth]=useState<'loading'|'login'|'denied'|'admin'>('loading'),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [works,setWorks]=useState<Work[]>([]),[editor,setEditor]=useState<Work|null>(null),[images,setImages]=useState<WorkImage[]>([]),[saved,setSaved]=useState(false),[dirty,setDirty]=useState(false);
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[preview,setPreview]=useState(false);
 useEffect(()=>{document.title='Works dashboard | DotByte'; const meta=document.createElement('meta');meta.name='robots';meta.content='noindex,nofollow';document.head.append(meta);
 if(!supabase){setAuth('login');return()=>meta.remove();}
 let active=true;
 const check=async()=>{try{const {data:{user}}=await supabase!.auth.getUser();if(!active)return;if(!user){setAuth('login');return;}const {data,error}=await supabase!.from('work_admins').select('user_id').eq('user_id',user.id).maybeSingle();if(error)throw error;setAuth(data?'admin':'denied');}catch(e){if(active){setNotice(message(e));setAuth('denied');}}};check();
 const {data}=supabase.auth.onAuthStateChange(()=>{setTimeout(check,0);});return()=>{active=false;data.subscription.unsubscribe();meta.remove();};},[]);
 useEffect(()=>{if(auth==='admin')loadWorks(true).then(setWorks).catch(e=>setNotice(message(e)));},[auth]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 async function run(action:()=>Promise<void>){setBusy(true);setNotice('');try{await action();}catch(e){setNotice(message(e));}finally{setBusy(false);}}
 const refresh=async()=>setWorks(await loadWorks(true));
 const change=(patch:Partial<Work>)=>{setEditor(w=>w?{...w,...patch}:w);setDirty(true);};
 const open=(work:Work|null)=>{if(dirty&&!window.confirm('Discard unsaved edits?'))return;setEditor(work?{...work}:emptyWork());setImages(work?.work_images||[]);setSaved(!!work);setDirty(false);setPreview(false);setNotice('');};
 async function save(e:FormEvent){e.preventDefault();if(!editor||!supabase)return;await run(async()=>{const {work_images,...payload}=editor;const {error}=await supabase!.from('works').upsert(payload);if(error)throw error;setSaved(true);setDirty(false);await refresh();setNotice(editor.status==='published'?'Project published.':'Draft saved.');});}
 async function upload(files:FileList|null){if(!files||!editor||!saved)return;await run(async()=>{for(const file of Array.from(files)){const blob=await compressImage(file),path=`${editor.id}/${crypto.randomUUID()}.webp`;const {error}=await supabase!.storage.from('work-images').upload(path,blob,{contentType:'image/webp'});if(error)throw error;const row={work_id:editor.id,path,alt:file.name.replace(/\.[^.]+$/,''),caption:'',sort_order:images.reduce((max,i)=>Math.max(max,i.sort_order),-1)+1+Array.from(files).indexOf(file)};const result=await supabase!.from('work_images').insert(row).select().single();if(result.error){await supabase!.storage.from('work-images').remove([path]);throw result.error;}const signed=await signImages([result.data]);setImages(list=>[...list,...signed]);}await refresh();setNotice('Images uploaded. The first image is your cover.');});}
 async function imageSave(image:WorkImage){await run(async()=>{const {error}=await supabase!.from('work_images').update({alt:image.alt,caption:image.caption}).eq('id',image.id);if(error)throw error;await refresh();setNotice('Image details saved.');});}
 async function move(index:number,direction:number){const updated=[...images];[updated[index],updated[index+direction]]=[updated[index+direction],updated[index]];await run(async()=>{const rows=updated.map((i,n)=>({id:i.id,work_id:i.work_id,path:i.path,alt:i.alt,caption:i.caption,sort_order:n}));const {error}=await supabase!.from('work_images').upsert(rows);if(error)throw error;setImages(updated);await refresh();});}
 async function removeImage(image:WorkImage){if(!window.confirm('Delete this image permanently?'))return;await run(async()=>{const {error}=await supabase!.storage.from('work-images').remove([image.path]);if(error)throw error;const result=await supabase!.from('work_images').delete().eq('id',image.id);if(result.error)throw result.error;setImages(list=>list.filter(i=>i.id!==image.id));await refresh();});}
 async function trash(work:Work){if(!work.deleted_at&&!window.confirm(`Move “${work.title}” to trash? It will disappear from the website.`))return;await run(async()=>{const {error}=await supabase!.from('works').update({deleted_at:work.deleted_at?null:new Date().toISOString(),status:'draft'}).eq('id',work.id);if(error)throw error;await refresh();setNotice(work.deleted_at?'Restored as a draft.':'Moved to trash.');});}
 async function permanent(work:Work){if(!window.confirm(`Permanently delete “${work.title}” and all its images? This cannot be undone.`))return;await run(async()=>{const paths=work.work_images?.map(i=>i.path)||[];if(paths.length){const {error}=await supabase!.storage.from('work-images').remove(paths);if(error)throw error;}const {error}=await supabase!.from('works').delete().eq('id',work.id);if(error)throw error;await refresh();setNotice('Project permanently deleted.');});}
 const filtered=works.filter(w=>(filter==='trash'?!!w.deleted_at:!w.deleted_at&&(filter==='all'||w.status===filter))&&w.title.toLowerCase().includes(search.toLowerCase()));
 return <main className="works-admin"><header><a href="/">dotbyte. <small>WORKS STUDIO</small></a>{auth==='admin'&&<button disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Discard unsaved edits and sign out?'))return;run(async()=>{const {error}=await supabase!.auth.signOut();if(error)throw error;setEditor(null);setWorks([]);setDirty(false);});}}>Sign out</button>}</header><div className="admin-content"><p role="status" className="admin-notice">{busy?'Working…':notice}</p>
 {!supabase?<section><h1>Connect your works studio</h1><p>Add the Supabase project URL and public key to the website environment, then restart the site.</p></section>:auth==='loading'?<p>Checking your session…</p>:auth==='login'?<form className="admin-login" onSubmit={e=>{e.preventDefault();run(async()=>{const {error}=await supabase!.auth.signInWithPassword({email,password});if(error)throw error;setPassword('');});}}><span className="micro">PRIVATE / DOTBYTE SYSTEMS</span><h1>Your work,<br/>in your hands.</h1><p>Sign in to manage projects, stories, and images.</p><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="admin-primary" disabled={busy}>Sign in →</button></form>:auth==='denied'?<section><h1>Admin access required</h1><p>This account does not have works access, or the database setup is incomplete.</p><button onClick={()=>run(async()=>{await supabase!.auth.signOut();setAuth('login');})}>Sign out</button></section>:editor?<>
 <div className="admin-toolbar"><button disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved edits?')){setEditor(null);setDirty(false);}}}>← All projects</button><button onClick={()=>setPreview(!preview)}>{preview?'Back to editor':'Preview'}</button></div>
 {preview?<WorkStory work={{...editor,work_images:images}}/>:<><form onSubmit={save}><fieldset disabled={busy}><h1>{saved?'Edit project':'A new beginning.'}</h1><div className="admin-fields"><label>Title<input required maxLength={150} value={editor.title} onChange={e=>change({title:e.target.value,...(!saved?{slug:slugify(e.target.value)}:{})})}/></label><label>URL slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={editor.slug} onChange={e=>change({slug:e.target.value})}/></label><label>Category<select value={editor.category} onChange={e=>change({category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Display order<input type="number" step="1" value={editor.sort_order} onChange={e=>change({sort_order:Number(e.target.value)})}/></label></div><label>Short description<textarea required maxLength={400} rows={2} value={editor.summary} onChange={e=>change({summary:e.target.value})}/></label><label>Project story<textarea rows={8} value={editor.description} onChange={e=>change({description:e.target.value})}/></label><label>Technologies (comma separated)<input value={editor.technologies.join(',')} onChange={e=>change({technologies:e.target.value.split(',')})}/></label><div className="admin-fields"><label>Live website<input type="url" pattern="https?://.*" value={editor.live_url} onChange={e=>change({live_url:e.target.value})}/></label><label>Source code link<input type="url" pattern="https?://.*" value={editor.github_url} onChange={e=>change({github_url:e.target.value})}/></label><label>Visibility<select value={editor.status} onChange={e=>change({status:e.target.value as Work['status']})}><option value="draft">Draft — only you</option><option value="published">Published — everyone</option></select></label><label className="admin-check"><input type="checkbox" checked={editor.featured} onChange={e=>change({featured:e.target.checked})}/> Featured on homepage</label></div><button className="admin-primary" type="submit">{editor.status==='published'?'Save & publish':'Save draft'}</button></fieldset></form>
 <section className="admin-images"><h2>Images & gallery</h2><p>The first image is your cover. Uploads and image edits save separately from project text.</p>{!saved?<p>Save a draft first to add images.</p>:<><label className="admin-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)upload(e.dataTransfer.files);}}>Drop images here or choose files<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{upload(e.target.files);e.target.value='';}}/><small>JPG, PNG, WebP · Up to 15 MB each · Automatically resized</small></label><div className="admin-image-grid">{images.map((i,n)=><div key={i.id}><img src={i.url} alt={i.alt}/><small>{n===0?'COVER':`IMAGE ${n+1}`}</small><label>Image description<input value={i.alt} onChange={e=>setImages(list=>list.map(item=>item.id===i.id?{...item,alt:e.target.value}:item))}/></label><label>Caption<input value={i.caption} onChange={e=>setImages(list=>list.map(item=>item.id===i.id?{...item,caption:e.target.value}:item))}/></label><div className="admin-toolbar"><button disabled={busy} onClick={()=>imageSave(i)}>Save details</button><button aria-label="Move image earlier" disabled={busy||n===0} onClick={()=>move(n,-1)}>←</button><button aria-label="Move image later" disabled={busy||n===images.length-1} onClick={()=>move(n,1)}>→</button><button disabled={busy} onClick={()=>removeImage(i)}>Delete</button></div></div>)}</div></>}</section></>}
 </>:<><div className="admin-heading"><div><span className="micro">YOUR WORK, ON DISPLAY</span><h1>Project library.</h1></div><button className="admin-primary" disabled={busy} onClick={()=>open(null)}>+ New project</button></div><div className="admin-toolbar"><input aria-label="Search projects" placeholder="Search projects…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter projects" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All projects</option><option value="draft">Drafts</option><option value="published">Published</option><option value="trash">Trash</option></select></div>{!filtered.length&&<p className="admin-empty">{works.length?'No projects match this view.':'Your next project starts here. Add your first work above.'}</p>}<div className="admin-projects">{filtered.map(w=><article key={w.id}><div><span className="micro">{w.category} / {w.deleted_at?'TRASH':w.status.toUpperCase()}</span><h2>{w.title}</h2><p>{w.summary}</p></div><div className="admin-toolbar">{!w.deleted_at&&<button disabled={busy} onClick={()=>open(w)}>Edit</button>}<button disabled={busy} onClick={()=>trash(w)}>{w.deleted_at?'Restore':'Move to trash'}</button>{w.deleted_at&&<button disabled={busy} onClick={()=>permanent(w)}>Delete forever</button>}</div></article>)}</div></>}
 </div></main>;
}
