import { useEffect, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { categories, loadWorks, safeLink, type Work } from '../lib/works';
import './Works.css';
export function WorkStory({work}:{work:Work}) { return <article className="work-story"><span className="micro">{work.category}</span><h1>{work.title}</h1><p className="work-summary">{work.summary}</p><div className="work-tags">{work.technologies.map(t=><span key={t}>{t}</span>)}</div>{work.work_images?.map(i=><figure key={i.id}><img src={i.url} alt={i.alt} loading="lazy"/>{i.caption&&<figcaption>{i.caption}</figcaption>}</figure>)}<p className="work-description">{work.description}</p><div className="work-links">{safeLink(work.live_url)&&<a href={safeLink(work.live_url)} target="_blank" rel="noopener noreferrer">Visit project ↗</a>}{safeLink(work.github_url)&&<a href={safeLink(work.github_url)} target="_blank" rel="noopener noreferrer">View source ↗</a>}</div></article>; }
export default function Works({detail=false}:{detail?:boolean}) {
 const [works,setWorks]=useState<Work[]>([]),[filter,setFilter]=useState('All'),[error,setError]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true; const refresh=()=>loadWorks().then(data=>{if(active){setWorks(data);setError(false);}}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);}); refresh(); const timer=setInterval(refresh, 300000);return()=>{active=false;clearInterval(timer);};},[]);
 const slug=window.location.pathname.split('/')[2]; const work=works.find(w=>w.slug===slug);
 useEffect(()=>{if(detail&&work)document.title=`${work.title} | DotByte Systems`;},[detail,work]);
 if(detail) return <main className="studio-wrap studio-section"><a href="/#works">← Back to DotByte</a>{loading?<p role="status">Loading project…</p>:error?<p role="alert">Couldn’t load this project. Please refresh to try again.</p>:work?<WorkStory work={work}/>:<h1>Project not found.</h1>}</main>;
 if(!works.length)return null;
 const visible=works.filter(w=>filter==='All'||w.category===filter).sort((a,b)=>Number(b.featured)-Number(a.featured));
 return <section id="works" className="studio-wrap studio-section"><div className="section-index micro"><span>SELECTED WORKS</span><span>IDEAS, MADE REAL.</span></div><div className="studio-heading"><h2>Built with purpose.<br/><span>Made to work.</span></h2><p>A closer look at what we design, develop, and bring to life.</p></div><div className="work-filters" aria-label="Filter projects">{['All',...categories].map(c=><button key={c} aria-pressed={filter===c} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="works-grid">{visible.map(w=><a className="work-card" key={w.id} href={`/works/${w.slug}`}><div className="work-cover">{w.work_images?.[0]?.url?<img src={w.work_images[0].url} alt={w.work_images[0].alt} loading="lazy"/>:<span>DOTBYTE / {w.category.toUpperCase()}</span>}</div><div className="work-card-copy"><span className="micro">{w.category}{w.featured?' / FEATURED':''}</span><h3>{w.title}<ArrowUpRight size={22}/></h3><p>{w.summary}</p></div></a>)}</div>{!visible.length&&<p>No projects in this category yet.</p>}</section>;
}
